---
- name: installing and configuring the HTTPD
  hosts: all 
  remote_user: ec2-user
  become: true
  become_method: sudo
  ignore_errors: true
  tasks:
  vars:
    web_pkg: httpd

  tasks:
  - name: installing the apache
    yum:
      name: "{{ web_pkg }}"
      state: present
  - name: make index file
    shell:
      cmd: touch /var/www/html/index.html && echo "HELLO FROM RPT" > /var/www/html/index.html
    notify: restart apache
  - name: make sure apache is running and enabled
    service:
      name: "{{ web_pkg }}"
      state: started
      enabled: yes
  handlers:
    - name: restart apache
      service:
        name: "{{ web_pkg }}"
        state: restarted
